// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function EchoTest() {
  return window['go']['main']['App']['EchoTest']();
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetLastScannedCard() {
  return window['go']['main']['App']['GetLastScannedCard']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function ListPorts() {
  return window['go']['main']['App']['ListPorts']();
}

export function ListenForNewCard() {
  return window['go']['main']['App']['ListenForNewCard']();
}

export function PingArduino() {
  return window['go']['main']['App']['PingArduino']();
}

export function ReadArduinoOutput() {
  return window['go']['main']['App']['ReadArduinoOutput']();
}

export function SendCommand(arg1) {
  return window['go']['main']['App']['SendCommand'](arg1);
}

export function SendCommandOnly(arg1) {
  return window['go']['main']['App']['SendCommandOnly'](arg1);
}

export function TestConnection() {
  return window['go']['main']['App']['TestConnection']();
}

export function TestLogEvent() {
  return window['go']['main']['App']['TestLogEvent']();
}
