// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function EchoTest():Promise<string>;

export function GetConnectionStatus():Promise<string>;

export function GetLastScannedCard():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function IsConnected():Promise<boolean>;

export function ListPorts():Promise<Array<string>>;

export function ListenForNewCard():Promise<string>;

export function PingArduino():Promise<string>;

export function ReadArduinoOutput():Promise<string>;

export function SendCommand(arg1:string):Promise<string>;

export function SendCommandOnly(arg1:string):Promise<string>;

export function TestConnection():Promise<boolean>;

export function TestLogEvent():Promise<void>;
